@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> Index
Index --> Login


Login --> Register
Login --> Login.Servlet
Register --> Login
Login.Servlet --> Welcome.jsp

state Login {

}

state Register{

}

state Logout{

}

state Login.Servlet {
  Login --> NewValueSelection
  NewValueSelection --> NewValuePreview : EvNewValue
  NewValuePreview --> NewValueSelection : EvNewValueRejected
  NewValuePreview --> NewValueSelection : EvNewValueSaved

  state NewValuePreview {
     State1 -> State2
  }


  state welcome.servlet{

  }

}

state Welcome.jsp{

}



@enduml